using System;
using System.Collections.Generic;
using Swish;
using System.IO;

namespace Swish.Tests
{
	class StataFunctionsTests
	{
		internal void StataBatchMode()
		{
			/// this tests that I can run stata in batch mode using the /b command argument 
			/// the test works by checking that an out put file is generated by running do script
			/// 

			string inputFile = GenerateMeanInputFile();

			string outputFile = Path.GetTempFileName();
			if (File.Exists(outputFile))
			{
				File.Delete(outputFile);
			}

			List<string> lines = new List<string>();
			lines.Add("clear");
			lines.Add("insheet using \"" + inputFile + "\"");
			lines.Add("collapse (mean) head4_mean=head4");
			lines.Add("outsheet using \"" + outputFile + "\", comma");

			string doFileName = Path.GetTempFileName();
			File.WriteAllLines(doFileName, lines.ToArray());

			string arguments = StataFunctions.BatchArgument + "\"" + doFileName + "\"";

			// there is also the log to deal with
			string workingDirectory = Path.GetDirectoryName(doFileName);

			int exitCode;
			string output;
			SwishFunctions.RunProcess(StataFunctions.StataExecutablePath, arguments, workingDirectory, false, out exitCode, out output);

			if (!File.Exists(outputFile))
			{
				throw new Exception();
			}
		}

		internal static string GenerateMeanInputFile()
		{
			string fileName = Path.GetTempFileName();
			if (File.Exists(fileName))
			{
				File.Delete(fileName);
			}

			List<string> lines = new List<string>();
			lines.Add("head2,head4,head6");
			lines.Add(".0606988,25,\"o\"");
			lines.Add(".401169,8,\"q\"	");
			lines.Add(".0395464,11,\"j\"");
			lines.Add(".4409516,18,\"u\"");
			lines.Add(".8912628,9,\"t\"");
			lines.Add(".5076998,15,\"x\"");
			lines.Add(".3962736,22,\"c\"");
			lines.Add(".5650445,7,\"w\"");
			lines.Add(".0135083,24,\"l\"");
			lines.Add(".8413007,19,\"g\"");
			lines.Add(".1266622,21,\"v\"");
			lines.Add(".3177137,26,\"b\"");
			lines.Add(".0492435,16,\"h\"");
			lines.Add(".9201018,14,\"y\"");
			lines.Add(".5963242,10,\"s\"");
			lines.Add(".80274,2,\"e\"	");
			lines.Add(".8763074,3,\"k\"");
			lines.Add(".1328795,1,\"r\"");
			lines.Add(".3056452,20,\"i\"");
			lines.Add(".2734099,23,\"a\"");
			lines.Add(".1731265,4,\"p\"");
			lines.Add(".7124847,5,\"m\"");
			lines.Add(".2824091,12,\"a\"");
			lines.Add(".0523007,0,\"z\"");
			lines.Add(".5270553,17,\"d\"");
			lines.Add(".3202022,6,\"f\"");
			lines.Add(".9965218,13,\"n\"");

			File.WriteAllLines(fileName, lines.ToArray());

			return fileName;
		}

		public const string MergeVariable = "head4";
		internal static void GenerateMergeInputFiles(out string inputFileName1, out string inputFileName2)
		{
			inputFileName1 = Path.GetTempFileName();
			if (File.Exists(inputFileName1))
			{
				File.Delete(inputFileName1);
			}

			List<string> lines = new List<string>();
			lines.Add("head2,head4");
			lines.Add("0.060698805,25");
			lines.Add("0.40116903,8");
			lines.Add("0.03954637,11");
			lines.Add("0.440951591,18");
			lines.Add("0.891262839,9");
			lines.Add("0.507699792,15");
			lines.Add("0.396273631,22");
			lines.Add("0.565044458,7");
			lines.Add("0.013508331,24");
			lines.Add("0.841300741,19");
			lines.Add("0.126662171,21");
			lines.Add("0.31771373,26");
			lines.Add("0.049243499,16");
			lines.Add("0.920101783,14");
			lines.Add("0.596324211,10");
			lines.Add("0.802740035,2");
			lines.Add("0.876307404,3");
			lines.Add("0.132879521,1");
			lines.Add("0.30564522,20");
			lines.Add("0.273409937,23");
			lines.Add("0.17312655,4");
			lines.Add("0.712484717,5");
			lines.Add("0.282409141,12");
			lines.Add("0.052300672,0");
			lines.Add("0.527055285,17");
			lines.Add("0.320202245,6");
			lines.Add("0.996521752,13");

			File.WriteAllLines(inputFileName1, lines.ToArray());

			inputFileName2 = Path.GetTempFileName();
			if (File.Exists(inputFileName2))
			{
				File.Delete(inputFileName2);
			}

			lines = new List<string>();
			lines.Add("head6,head4");
			lines.Add("o,15");
			lines.Add("q,17");
			lines.Add("j,9");
			lines.Add("u,21");
			lines.Add("t,20");
			lines.Add("x,24");
			lines.Add("c,2");
			lines.Add("w,23");
			lines.Add("l,11");
			lines.Add("g,6");
			lines.Add("v,22");
			lines.Add("b,1");
			lines.Add("h,7");
			lines.Add("y,25");
			lines.Add("s,19");
			lines.Add("e,4");
			lines.Add("k,10");
			lines.Add("r,18");
			lines.Add("i,8");
			lines.Add("a,0");
			lines.Add("p,16");
			lines.Add("m,12");
			lines.Add("a,14");
			lines.Add("z,26");
			lines.Add("d,3");
			lines.Add("f,5");
			lines.Add("n,13");

			File.WriteAllLines(inputFileName2, lines.ToArray());
		}



	}
}
































